# Generated by Django 5.0.6 on 2024-05-26 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pt1', 'PT1'), ('pt2', 'PT2'), ('idp', 'IDP')], max_length=3)),
                ('scope', models.CharField(choices=[('IEEE', 'IEEE'), ('Journal', 'Journal')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='project.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
