# Generated by Django 5.0.6 on 2024-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_denied_reason_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(default='hi'),
        ),
    ]
