# Generated by Django 5.0.6 on 2024-05-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_scope_project_research'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='research',
            new_name='research_paper',
        ),
    ]
