# Generated by Django 5.0.6 on 2024-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_research_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_domain',
            field=models.CharField(default='Cyber', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Professional Training 1', 'Professional Training 1'), ('Interdisciplinary Project', 'Interdisciplinary Project'), ('Project Work', 'Project Work')], max_length=100),
        ),
    ]
