# Generated by Django 5.0.6 on 2024-06-11 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_project_domain_alter_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'member')},
        ),
    ]
